# Base stage
FROM golang:alpine
WORKDIR /go/src/golang-demos/go-crontab/crontab
COPY . .
RUN apk --update add --no-cache --virtual dependency git \
    && go get -d -v ./... \
    && apk del dependency
EXPOSE 3000